k9s:
  refreshRate: 2
  logBufferSize: 1000
  logRequestSize: 200
  currentContext: mycluster
  currentCluster: mycluster
  clusters:
    mycluster:
      namespace:
        active: all
        favorites:
        - all
        - default
      view:
        active: po
